name: First deployment

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.jobs
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: Build application
        run: npm run build

  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Ssh to the server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/projects

            if [ ! -d ".git" ]; then
              git clone https://github.com/Sayedtaqi313/nest-one.git .
            else
              git pull
            fi

            docker compose up --build -d
